### ISSUE TITLE
Functional Issue - How to register using MSAL library using xamarin forms

### ISSUE THREAD

**Issue by viveknegi51288** [msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps#13]
# Functional Issue Report
Hi, I have developed a xamarin forms application and able to get azure access token in both android and ios.

Now I have to integrate Intunes sdk to the app, I did it and able to registered IOS application as steps given in your documentation . Now I need to registered user from android but in your documentation there is no where mentioned how to use MSAL library in android.

 

### Taskr Application Type
Issue is with the Xamarin.Forms app.*

### Description
Not able to registered user on Intunes using MSAL library. Every time getting NON_Licenced user but user is licensed,

### Code and Settings Changes
Instead of ADAL i am using MSAL, and able to get access token , now please help me to register the user in android suing MSAL library.

### Expected Behavior
User should registered using MSAL library in android also.

### Logs
*Please [capture MAM logs from the Intune Company Portal app](https://docs.microsoft.com/en-us/intune-user-help/send-logs-to-your-it-admin-by-email-android#upload-and-email-logs-from-company-portal) and report the corresponding incident ID here.*
 - **Incident ID**: 

### Device Information
 - **Device Make and Model:**Samsung note 8
 - **OS API:** 28

### Xamarin Information
- **Visual Studio Version:** 2019

**Comment by viveknegi51288** [comment]
@meghandaly @msintuneappsdk  @cofitz1  please confirm whether android intune sdk is compatible to MSAL library. Please help

**Comment by bgavrilMS** [comment]
@viveknegi51288  - I confirm that MSAL is the only supported library for Intune + Xamarin. ADAL is deprecated and you should not use it. We are trying to get the sampels and docs updated.

**Comment by bgavrilMS** [comment]
@viveknegi51288 - please see https://github.com/msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps/issues/15 for more details on how to use MSAL

**Comment by meghandaly** [comment]
Sample has been updated to MSAL, please review changes :)
