### ISSUE TITLE
Functional Issue - ADAL is deprecated, sample should use MSAL

### ISSUE THREAD

**Issue by bgavrilMS** [msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps#15]
# Functional Issue Report
Please use MSAL for integration and not ADAL. ADAL is on a deprecation path and has MAJOR problems in the Android + Intune scenario.

Several 1st party and 3rd party customers have already used MSAL successfully - see some testimonials [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki#testimonials).

Sample Xamarin app that shows MSAL integration [here](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/master/2-With-broker).

ADAL -> MSAL migration guide [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-migration-ios-broker).

**Comment by JamestsaiTW** [comment]
Is there any update for "Sample Intune Xamarin.Android/Xamarin.Forms Apps" by using MSAL?

**Comment by bgavrilMS** [comment]
@JamestsaiTW - the MSAL team maintain their own sample which demonstrates broker (Intune) + Xamarin: https://github.com/azure-samples/active-directory-xamarin-native-v2

**Comment by JamestsaiTW** [comment]
@bgavrilMS Thanks!
