### ISSUE TITLE
TaskrForms.Android sample code build failed in Visual Studio 2019

### ISSUE THREAD

**Issue by JamestsaiTW** [msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps#2]
In Visual Studio 2019 (Version 16.0.3)

Output Message:

--- 
` 
1>------ Rebuild All started: Project: TaskrForms, Configuration: Release Any CPU ------
1>TaskrForms -> C:\tmp\Taskr-Sample-Intune-Xamarin\TaskrForms\TaskrForms\bin\Release\netstandard2.0\TaskrForms.dll
2>------ Rebuild All started: Project: TaskrForms.Android, Configuration: Release Any CPU ------
2>C:\Users\<User Account>\.nuget\packages\microsoft.intune.mam.remapper.tasks\0.1.4119.2\build\MonoAndroid10\Microsoft.Intune.MAM.Remapper.Tasks.targets(53,5): error MSB4044: The "ResolveAssemblies" task was not given a value for the required parameter "TargetFrameworkVersion".
2>  No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2193,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2193,5): error MSB4018: System.IO.FileNotFoundException: Could not load assembly 'TaskrForms.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2193,5): error MSB4018: File name: 'TaskrForms.Android.dll'
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2193,5): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2193,5): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2193,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2193,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2193,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2193,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
`

--- 

Error List:
![image](https://user-images.githubusercontent.com/9651229/57584604-e6e16080-750f-11e9-9fbb-48cd5f79c1d0.png)  

--- 

When I use Visual Studio 2017 and build this sample code, it's success. How to solve it? Thanks.

**Comment by meghandaly** [comment]
Hi @JamestsaiTW this is due to an issue with our SDK Xamarin bindings. 

The issue is being tracked here: https://github.com/msintuneappsdk/intune-app-sdk-xamarin/issues/28 and I have added a temporary workaround to that issue while we prepare our next release of the bindings.

Once the update to the bindings is released I will also be updating our sample apps.

**Comment by JamestsaiTW** [comment]
OK, I got it. Please fix it as soon as possible, thanks.

**Comment by meghandaly** [comment]
The Taskr Forms app has been updated and will now build properly in VS2019.
