### ISSUE TITLE
Default enrollment,  example for Xamarin Forms

### ISSUE THREAD

**Issue by Totonti** [msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps#3]
Hi, 
I am trying to use the default enrollment in the Android Xamarin Forms application, but I do not know exactly how to implement it.

My scenario is as follows: the Company Portal is installed, the user authenticates in the portal and performs the download and installation of the application. When starting the application, I need to collect the configuration policy that the app use so that it can start correctly (in this case, the FTP credentials to download some necessary configuration files).

So, I need to access the configuration policy of the application, but that function: _configManager.GetAppConfig requests an identity (user) as a parameter, so I do not know if in this case it is correct to use the default registration or I have to use ADAL in order to have the user

I've been looking at the TaskrForms sample application, but in this case you have to register the application in Azure and use ADAL and that's what, if possible, I want to avoid.

If you can help me clarify the subject, I would be very grateful.
Thank you

**Comment by Totonti** [comment]
Hi, 
I have found the example sample **patlewis-MSFT/XamarinAndroidIntuneDefaultEnrollment**, and from what I see it is necessary to register the app in Azure to obtain the ClientID. Is this correct?
Is there any way to avoid registering the app in AD?
Thanks

**Comment by Totonti** [comment]
hi,
I am testing without using the ClientID and in the output window I see this:

 ```
05-22 18:32:42.411 I/MAMInfo (13074): MAMInfo initialized. Debug=false, UseTestAgent=false, ManagedDialogDisabled=false, DeprecationDialogDisabled=false, PolicyRequired=false, MultiIdentityEnabled=false, FullBackupContent=true, UseDefaultEnrollment=false, ExceptionOnInit=false

05-22 18:32:42.423 I/MAMWERetryScheduler(13074): task thread waiting for tasks.
Loaded assembly: AndHUD.dll [External]05-22 18:32:42.428 I/Signatures(13074): Company Portal signature verified.

05-22 18:32:42.438 I/MAMInfo (13074): MAMInfo initialized. Debug=false, UseTestAgent=false, ManagedDialogDisabled=false, DeprecationDialogDisabled=false, PolicyRequired=false, MultiIdentityEnabled=false, FullBackupContent=true, UseDefaultEnrollment=false, ExceptionOnInit=false, Debuggable=false
05-22 18:32:42.445 I/Signatures(13074): Company Portal signature verified.
05-22 18:32:42.411 I/MAMInfo (13074): MAMInfo initialized. Debug=false, UseTestAgent=false, ManagedDialogDisabled=false, DeprecationDialogDisabled=false, PolicyRequired=false, MultiIdentityEnabled=false, FullBackupContent=true, UseDefaultEnrollment=false, ExceptionOnInit=false
05-22 18:32:42.423 I/MAMWERetryScheduler(13074): task thread waiting for tasks.
Loaded assembly: AndHUD.dll [External]05-22 18:32:42.428 I/Signatures(13074): Company Portal signature verified.

05-22 18:32:42.438 I/MAMInfo (13074): MAMInfo initialized. Debug=false, UseTestAgent=false, ManagedDialogDisabled=false, DeprecationDialogDisabled=false, PolicyRequired=false, MultiIdentityEnabled=false, FullBackupContent=true, UseDefaultEnrollment=false, ExceptionOnInit=false, Debuggable=false
05-22 18:32:42.445 I/Signatures(13074): Company Portal signature verified.
```

and it does not do anything else, I do not see any reference to MAM in the output window.

**Comment by meghandaly** [comment]
@Totonti We are looking into making a version of Taskr available that is configured for default enrollment.

The main changes required are outlined in the [default enrollment](https://docs.microsoft.com/en-us/intune/app-sdk-android#default-enrollment-optional) section of SDK documentation. The two manifest values need to be included in the Android manifest and there should be no calls to `MAMEnrollmentManager` in your application.

With default enrollment a client ID does not need to be registered. 

Your logs indicate MAM was properly initialized. What behavior are you expecting? Would you be willing to share your app?

**Comment by Totonti** [comment]
Hi @meghandaly ,
I've finally made it work in Android, in both cases ADAL and default enrollment, thank you.
I was writing the default enrollment tags outside the <application> tag in manifest... aghhhh!.

Now I have a different problem in iOS with app config data:
https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/36#issue-449828028

Thank you
