### ISSUE TITLE
Different user (other  than registered device user) is not able to login to the app

### ISSUE THREAD

**Issue by hverma11** [msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps#5]
@meghandaly 
Hi Meghan,
   I have deployed (debugging still not working on android) the application to enrolled device using workspace. Have few questions:

 Scenario 1: 
      Device is registered to user X and if user X login to the app, it works fine. 
 Scenario 2 :
      Device is registered to user X and if another valid AD user Y login to the app, it throws me on the screen saying : 

Your sign-in was successful, but your admin requires your device to be managed by ************** to access this resource

![screenshot](https://user-images.githubusercontent.com/10015487/60058752-c0812880-973d-11e9-960f-4a6855cc61ae.jpg)

I can see on the provided screenshot: Device Identifier is Not available and Device stat eis unregistered. 

But the device is registered in Intune.. Can you please guide me, pretty new to Intune world.

Regards,
Hemant

**Comment by meghandaly** [comment]
@hverma11 The behavior you are encountering is by design. The device is registered to Intune for account X. To access resources for account Y, you would need to register the device to that user. 

Also, welcome to the Intune world! For more information in the future please refer to the [Intune documentation](https://docs.microsoft.com/intune/).

**Comment by hverma11** [comment]
Great.. Thanks for explanation.

I do have some Kiosk devices that will be used by multiple users. Is there any solution for this scenario in Intune?

**Comment by aanavath** [comment]
Hi @hverma11 there is a notion of Android Enterprise dedicated devices and these devices are not associated with any user. This is some general information on that scenario: https://docs.microsoft.com/en-us/intune/android-kiosk-enroll. When the device itself is managed, there may not be a need to use app protection policies itself. Hope this helps.
